on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy directory
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local_path: '.output/*'
          remote_path: '/opt/ardeco/web'
          sftp_only: true
